using System;

namespace backend.Utils
{
    public static class BattleDialogLines
    {
        // Openers för ny strid
        public static string[] EncounterOpeners(string playerName, int playerLevel, string enemyName) => new[]
        {
            $"A wild {enemyName} appears! It looks dangerous...",
            $"{playerName} (Lv {playerLevel}) cracks their knuckles and grins at the {enemyName}.",
            $"{enemyName.Capitalize()} slides in like it's the final boss in a 90s arcade game!",
            $"You lock eyes with the {enemyName} – neither of you can blink.",
            $"It's showdown time! {enemyName.Capitalize()} vs {playerName}!",
            $"Thunder cracks. {enemyName.Capitalize()} steps forward with a menacing glare.",
            $"The ground shakes as {enemyName.Capitalize()} challenges you.",
            $"{enemyName.Capitalize()} does a dramatic anime entrance. It's ON!",
            $"Did the {enemyName} just wink at you? That's unsettling.",
            $"You feel like you've seen the {enemyName} somewhere before...",
            $"Cue the boss music! {enemyName.Capitalize()} wants to fight.",
            $"A hush falls over the battlefield as {enemyName} appears.",
            $"The {enemyName} drops in from the ceiling, ready to throw hands.",
            $"Is that... the legendary {enemyName}? Your knees are weak, arms are heavy.",
            $"The {enemyName} smells like trouble (and possibly cheese).",
            $"{playerName} checks their pockets for snacks, but the {enemyName} only hungers for battle.",
            $"{enemyName.Capitalize()} emerges from a suspicious bush.",
            $"A tumbleweed rolls by as you face off with the {enemyName}.",
            $"Somewhere, a narrator whispers: 'And so, the duel begins...'",
            $"You hear the {enemyName} humming its own theme song.",
            $"The {enemyName} points at you and challenges you to a staring contest.",
            $"A breeze picks up. You wonder if it’s the {enemyName}’s breath.",
            $"Your phone vibrates—it's just a message: 'Good luck against {enemyName}!'",
            $"{playerName} feels a disturbance in the force as {enemyName.Capitalize()} arrives.",
            $"The {enemyName} trips on its way in but pretends it was intentional.",
            $"Both you and the {enemyName} reach for the last slice of pizza. It's WAR.",
            $"Suddenly, you're surrounded by mist—and out steps the {enemyName}.",
            $"{enemyName.Capitalize()} poses dramatically, expecting applause.",
            $"{playerName} suddenly regrets all their life choices as {enemyName} appears.",
            $"The sky darkens as {enemyName.Capitalize()} enters the arena.",
            $"Your heart skips a beat—was it fear, or just too much caffeine?",
            $"This encounter is so epic, it deserves its own Netflix series."
        };

        // Spelarens attack-openers
        public static string[] PlayerOpeners(string playerName, string enemyName) => new[]
        {
            $"⚔️ {playerName} charges forward and swings at the {enemyName}!",
            $"{playerName} does a cartwheel and throws a punch at the {enemyName}!",
            $"{playerName} yells 'YEET!' and hurls themselves at the {enemyName}.",
            $"{playerName} uses 100% of their remaining dignity to deliver an attack.",
            $"{playerName} slips on a banana peel but still manages to attack the {enemyName}.",
            $"{playerName} whips out a rubber chicken and bonks the {enemyName}.",
            $"{playerName} does a spinny anime sword move and aims at the {enemyName}.",
            $"{playerName} shouts 'FOR NARNIA!' and runs at the {enemyName}.",
            $"{playerName} throws a shoe at the {enemyName}, hoping for the best.",
            $"{playerName} attempts an epic somersault and lands... somewhere near the {enemyName}.",
            $"{playerName} dabs aggressively in the {enemyName}'s general direction.",
            $"{playerName} recites their shopping list to distract the {enemyName} before attacking.",
            $"{playerName} launches a sneak attack using their best dad joke.",
            $"{playerName} screams 'PLOT TWIST!' and goes in swinging.",
            $"{playerName} tries to summon a fireball but only manages static electricity.",
            $"{playerName} moonwalks up to the {enemyName} and delivers a stylish slap.",
            $"{playerName} brandishes an imaginary sword and shouts 'EXCALIBUR!'",
            $"{playerName} does a dramatic anime transformation... that no one asked for.",
            $"{playerName} attempts a ninja move, but only achieves mild confusion.",
            $"{playerName} challenges the {enemyName} to rock-paper-scissors—then attacks anyway.",
            $"{playerName} starts singing and attacks on the high note.",
            $"{playerName} yells 'THIS IS SPARTA!' and dropkicks the {enemyName}.",
            $"{playerName} flosses so hard that the {enemyName} is momentarily stunned.",
            $"{playerName} pretends they're in a cooking show, then hits the {enemyName} with a frying pan.",
            $"{playerName} attempts to reason with the {enemyName}, then changes their mind and attacks.",
            $"{playerName} tosses glitter everywhere and charges heroically.",
            $"{playerName} asks the {enemyName} for its WiFi password before attacking.",
            $"{playerName} attempts to perform a TikTok dance and uses the momentum to strike.",
            $"{playerName} claims to be 'built different' and rushes in.",
            $"{playerName} winks at the {enemyName} and attacks while it's confused.",
            $"{playerName} does a full power-rangers pose before leaping at the {enemyName}.",
            $"{playerName} rolls for initiative, then attacks anyway."
        };

        // Critical hit
        public static string[] CritLines(string playerName, int damage) => new[]
        {
            $"💥 **Critical hit!** {playerName} channels their inner anime protagonist and deals a jaw-dropping {damage} damage!",
            $"💥 **Critical hit!** {playerName}'s attack goes SUPER SAIYAN and deals {damage} damage!",
            $"💥 **Critical hit!** {playerName} lands an epic hit for {damage} damage!",
            $"💥 **Critical hit!** {playerName} unleashes a forbidden meme attack for {damage} damage!",
            $"💥 **Critical hit!** {playerName} yells 'TOP TEN ANIME BATTLES!' and delivers {damage} damage!",
            $"💥 **Critical hit!** {playerName} does a backflip and double-punches for {damage} damage!",
            $"💥 **Critical hit!** {playerName} yells 'MOM, GET THE CAMERA!' and strikes for {damage} damage!",
            $"💥 **Critical hit!** {playerName}'s attack was so strong, the {damage} damage echoes through time!",
            $"💥 **Critical hit!** {playerName} delivers {damage} damage with a move banned in three countries.",
            $"💥 **Critical hit!** {playerName} hits so hard, the screen shakes ({damage} damage)!",
            $"💥 **Critical hit!** {playerName} crits with the power of a thousand rubber chickens for {damage} damage!",
            $"💥 **Critical hit!** {playerName} pulls off a 360-no-scope for {damage} damage!",
            $"💥 **Critical hit!** {playerName} presses 'F' to pay respects... and deals {damage} damage.",
            $"💥 **Critical hit!** {playerName} shouts 'LEEEEEROY JENKINS!' and smashes for {damage} damage!",
            $"💥 **Critical hit!** {playerName}'s pure drip deals {damage} damage.",
            $"💥 **Critical hit!** {playerName} deals {damage} damage and unlocks the secret boss music.",
            $"💥 **Critical hit!** {playerName} uses ultra instinct! {damage} DAMAGE!",
            $"💥 **Critical hit!** {playerName} hits with maximum plot armor for {damage} damage.",
            $"💥 **Critical hit!** {playerName} causes a glitch in the matrix: {damage} damage!",
            $"💥 **Critical hit!** {playerName} invokes the power of friendship for {damage} damage.",
            $"💥 **Critical hit!** {playerName} combines all the Infinity Stones and snaps for {damage} damage.",
            $"💥 **Critical hit!** {playerName} lands a hit so spicy, it does {damage} damage and burns calories.",
            $"💥 **Critical hit!** {playerName} crits so hard, even the devs are impressed: {damage} damage.",
            $"💥 **Critical hit!** {playerName}'s mom calls and says she's proud of the {damage} damage.",
            $"💥 **Critical hit!** {playerName} goes full super saiyan 2 and wrecks for {damage} damage.",
            $"💥 **Critical hit!** {playerName} hits with the force of pure caffeine for {damage} damage.",
            $"💥 **Critical hit!** {playerName} lands a no-context uppercut for {damage} damage.",
            $"💥 **Critical hit!** {playerName} invokes an old meme for {damage} damage.",
            $"💥 **Critical hit!** {playerName}'s attack was so cringe, it did {damage} damage.",
            $"💥 **Critical hit!** {playerName} yells 'HADOUKEN!' and dishes out {damage} damage.",
            $"💥 **Critical hit!** {playerName} attacks with such finesse, the {damage} damage is art.",
        };


        // Enemy HP minskning
        public static string[] EnemyHpLines(string enemyName, int hp, int maxHp) => new[]
        {
            $"The {enemyName} staggers! {enemyName.Capitalize()} HP now at {hp}/{maxHp}.",
            $"{enemyName.Capitalize()} now has {hp}/{maxHp} HP remaining.",
            $"{enemyName.Capitalize()} looks worried: {hp}/{maxHp} HP left.",
            $"A bead of sweat rolls down the {enemyName}'s face. ({hp}/{maxHp} HP)",
            $"You hear boss music get quieter—{enemyName} only has {hp}/{maxHp} HP!",
            $"{enemyName.Capitalize()} tries to hide a limp: {hp}/{maxHp} HP.",
            $"The {enemyName} looks at you with fear in its eyes. ({hp}/{maxHp} HP left!)",
            $"{enemyName.Capitalize()} is regretting its life choices. ({hp}/{maxHp} HP)",
            $"Someone call an ambulance for {enemyName}—{hp}/{maxHp} HP left.",
            $"{enemyName.Capitalize()} wobbles but refuses to fall. ({hp}/{maxHp})",
            $"{enemyName.Capitalize()} is hanging on by a thread! {hp}/{maxHp} HP remains.",
            $"{enemyName.Capitalize()} uses all its willpower to stay standing ({hp}/{maxHp} HP).",
            $"{enemyName.Capitalize()} is at {hp}/{maxHp} HP and starts to panic.",
            $"The {enemyName} looks at the camera like it's on The Office. ({hp}/{maxHp})",
            $"{enemyName.Capitalize()} is still up—but just barely! {hp}/{maxHp} HP.",
            $"You can practically smell the fear. {enemyName.Capitalize()} HP: {hp}/{maxHp}.",
            $"{enemyName.Capitalize()} starts Googling 'How to survive adventurers' ({hp}/{maxHp} HP).",
            $"The {enemyName}'s confidence drops: {hp}/{maxHp} HP.",
            $"{enemyName.Capitalize()} gets dramatic and pretends to faint ({hp}/{maxHp} HP left).",
            $"{enemyName.Capitalize()} tries to call for backup, but it's just you. ({hp}/{maxHp} HP)",
            $"The {enemyName} is holding on for dear life! ({hp}/{maxHp})",
            $"You see cartoon stars above {enemyName}'s head: {hp}/{maxHp} HP.",
            $"The {enemyName} uses 'look pitiful'—it only has {hp}/{maxHp} HP.",
            $"Blood, sweat, and tears—{enemyName.Capitalize()} at {hp}/{maxHp} HP.",
            $"{enemyName.Capitalize()} uses band-aids, but it's not enough. ({hp}/{maxHp} HP)",
            $"The {enemyName} whispers 'this isn't even my final form' ({hp}/{maxHp} HP).",
            $"A single tear falls from the {enemyName}'s eye: {hp}/{maxHp} HP.",
            $"{enemyName.Capitalize()} offers you a truce at {hp}/{maxHp} HP.",
            $"The {enemyName} looks ready to rage-quit at {hp}/{maxHp} HP.",
            $"{enemyName.Capitalize()} tries to hit 'undo' on the fight ({hp}/{maxHp} HP left)."
        };

        // Victory lines
       public static string[] VictoryLines(string playerName, string enemyName) => new[]
        {
            $"🏆 **Victory!** The {enemyName} explodes into confetti and is defeated!",
            $"🏆 **Victory!** {playerName} just flexed too hard. The {enemyName} faints!",
            $"🏆 **Victory!** The {enemyName} can't handle the cringe and surrenders.",
            $"🏆 **Victory!** The {enemyName} collapses and is defeated!",
            $"🏆 **Victory!** {playerName} does a victory dance while the {enemyName} lies defeated.",
            $"🏆 {playerName} flosses on the {enemyName}'s remains.",
            $"🏆 The {enemyName} evaporates into meme dust. {playerName} stands tall!",
            $"🏆 {playerName} claims victory, and the {enemyName} rage-quits.",
            $"🏆 The {enemyName} leaves the battlefield to become an influencer.",
            $"🏆 {playerName} posts a selfie over the {enemyName}'s body.",
            $"🏆 The {enemyName} admits defeat and asks for your autograph.",
            $"🏆 {playerName} wins! The {enemyName} is now trending on fail compilations.",
            $"🏆 {playerName} shouts 'EZ!' as the {enemyName} logs off.",
            $"🏆 The {enemyName} tries to uninstall life itself. Too late!",
            $"🏆 {playerName} celebrates with a Fortnite dance over the {enemyName}.",
            $"🏆 The {enemyName} fades into a TikTok cringe montage.",
            $"🏆 {playerName} wins so hard, the {enemyName}'s ancestors feel it.",
            $"🏆 {playerName} wipes sweat, takes a bow, and the {enemyName} is out.",
            $"🏆 {playerName} throws a party. The {enemyName} isn't invited.",
            $"🏆 The {enemyName} forfeits and hands {playerName} a coupon for free pizza.",
            $"🏆 {playerName} blasts a kazoo solo as the {enemyName} vanishes.",
            $"🏆 The {enemyName} has left the chat.",
            $"🏆 {playerName} wins! The {enemyName} drops loot and existential dread.",
            $"🏆 The {enemyName} disintegrates in a puff of glitter.",
            $"🏆 {playerName} dabs on the haters (and the {enemyName}).",
            $"🏆 The {enemyName} calls their mom to come pick them up.",
            $"🏆 {playerName} adds a win to their highlight reel.",
            $"🏆 {playerName} levels up, while the {enemyName} goes to therapy.",
            $"🏆 The {enemyName} yeets itself into the void.",
            $"🏆 {playerName} flexes. The {enemyName} can't even.",
        };

        // Enemy actions
        public static string[] EnemyActions(string enemyName) => new[]
        {
            $"😡 The {enemyName} becomes enraged and counterattacks!",
            $"🤪 The {enemyName} starts screaming random TikTok audios and attacks!",
            $"👺 The {enemyName} insults your fashion sense before striking.",
            $"😈 The {enemyName} attempts a triple backflip attack!",
            $"😤 The {enemyName} roars 'I am the danger!' and lunges at you!",
            $"🤡 The {enemyName} tells a bad dad joke and then attacks.",
            $"👹 The {enemyName} throws a rock and hopes for the best.",
            $"🦖 The {enemyName} tries to do a dinosaur roar but just ends up coughing.",
            $"🧙‍♂️ The {enemyName} casts a spell that backfires and hits itself!",
            $"👻 The {enemyName} tries to scare you but just ends up falling over.",
            $"🕺 The {enemyName} moonwalks threateningly before attacking.",
            $"😳 The {enemyName} forgets what it was doing but attacks anyway.",
            $"🍕 The {enemyName} takes a bite of cold pizza, gets energized, and attacks.",
            $"🎤 The {enemyName} drops a diss track about you and attacks.",
            $"🍌 The {enemyName} throws a banana peel on the ground.",
            $"📸 The {enemyName} takes a selfie mid-battle, then attacks.",
            $"🎲 The {enemyName} rolls a D20 for style, then swings.",
            $"🦶 The {enemyName} tries to trip you with its foot.",
            $"🎭 The {enemyName} dramatically monologues before striking.",
            $"🐸 The {enemyName} dabs, croaks, and attacks.",
            $"🏃 The {enemyName} runs in circles to confuse you, then attacks.",
            $"📢 The {enemyName} yells 'WORLDSTAR!' and throws a punch.",
            $"🧻 The {enemyName} tries to TP your base, then attacks.",
            $"🤖 The {enemyName} does a robot dance and attacks.",
            $"🎮 The {enemyName} mashes buttons and launches a combo move.",
            $"🌈 The {enemyName} throws glitter everywhere, then attacks.",
            $"🦷 The {enemyName} tries to bite you with imaginary teeth.",
            $"🧤 The {enemyName} slaps you with a glove and attacks.",
            $"🦞 The {enemyName} does a crab walk into battle.",
            $"😬 The {enemyName} nervously attacks after telling a really bad joke."
        };

        // Enemy attack lines
        public static string[] EnemyAttackLines(string enemyName) => new[]
        {
            $"The {enemyName} raises its rusty sword high and swings it furiously!",
            $"The {enemyName} lunges forward with a wild stab!",
            $"The {enemyName} jumps and tries to bite you with sharp teeth!",
            $"The {enemyName} throws a moldy shoe at your head!",
            $"The {enemyName} attempts a WWE suplex, but just falls on you.",
            $"The {enemyName} tries to trip you with its own nose hair!",
            $"The {enemyName} slaps you with a slice of wet bread!",
            $"The {enemyName} does a dramatic spin and accidentally hits itself!",
            $"The {enemyName} tries to uppercut you like in Mortal Kombat.",
            $"The {enemyName} throws a handful of sand in your direction.",
            $"The {enemyName} pelts you with a barrage of stale popcorn.",
            $"The {enemyName} swings a baguette like it's Excalibur.",
            $"The {enemyName} attempts a flying kick and almost pulls a hamstring.",
            $"The {enemyName} throws a rubber duck. It hurts more than you’d expect.",
            $"The {enemyName} uses 'Slap Chop!'—ouch!",
            $"The {enemyName} pulls out nunchucks and promptly drops them.",
            $"The {enemyName} attempts a Hadouken, but it's just a light tap.",
            $"The {enemyName} tries to roast you—emotionally AND physically.",
            $"The {enemyName} launches a potato like a missile.",
            $"The {enemyName} claps menacingly and charges.",
            $"The {enemyName} does a fake-out, then headbutts you.",
            $"The {enemyName} hurls a water balloon filled with pickle juice.",
            $"The {enemyName} charges with reckless abandon and questionable technique.",
            $"The {enemyName} does an interpretive dance, then tackles you.",
            $"The {enemyName} throws a Pokéball at your face.",
            $"The {enemyName} swings a pool noodle, but somehow it still hurts.",
            $"The {enemyName} bites your shoe. It was expensive.",
            $"The {enemyName} tries to trip you, but you both fall over.",
            $"The {enemyName} goes for a wrestling move it saw on TV.",
            $"The {enemyName} snaps a towel at you, gym locker-room style!"
        };

        // Enemy critical hit lines
        public static string[] EnemyCritLines(string enemyName, int damage) => new[]
        {
            $"💥 **Critical hit!** The {enemyName} spins like a fidget spinner and deals {damage} damage!",
            $"💥 **Critical hit!** The {enemyName} hits you with peak rage for {damage} damage!",
            $"💥 **Critical hit!** The {enemyName} yells 'GO {enemyName.ToUpper()} MODE' and deals {damage} damage!",
            $"💥 **Critical hit!** The {enemyName} goes berserk and hits you for {damage} damage!",
            $"💥 **Critical hit!** The {enemyName} delivers a surprise left hook for {damage} damage!",
            $"💥 **Critical hit!** The {enemyName} pulls out the forbidden move for {damage} damage!",
            $"💥 **Critical hit!** The {enemyName} summons all its ancestors for {damage} damage!",
            $"💥 **Critical hit!** The {enemyName} goes Super Saiyan for {damage} damage!",
            $"💥 **Critical hit!** The {enemyName} drops a giant rubber duck for {damage} damage!",
            $"💥 **Critical hit!** The {enemyName} uses ultra meme energy for {damage} damage!",
            $"💥 **Critical hit!** The {enemyName} throws a critical roast for {damage} damage!",
            $"💥 **Critical hit!** The {enemyName} dropkicks you into next week for {damage} damage!",
            $"💥 **Critical hit!** The {enemyName} throws a meteor-sized potato for {damage} damage!",
            $"💥 **Critical hit!** The {enemyName} lands a 360-no-scope for {damage} damage!",
            $"💥 **Critical hit!** The {enemyName} yells 'THIS IS SPARTA!' and deals {damage} damage!",
            $"💥 **Critical hit!** The {enemyName} headbutts you with cosmic force for {damage} damage!",
            $"💥 **Critical hit!** The {enemyName} channeles its inner Karen for {damage} damage!",
            $"💥 **Critical hit!** The {enemyName} launches you into a cutscene for {damage} damage!",
            $"💥 **Critical hit!** The {enemyName} whips out a critical rubber chicken for {damage} damage!",
            $"💥 **Critical hit!** The {enemyName} does a backflip crit for {damage} damage!",
            $"💥 **Critical hit!** The {enemyName} uses a legendary slap for {damage} damage!",
            $"💥 **Critical hit!** The {enemyName} quotes Shakespeare and destroys you for {damage} damage!",
            $"💥 **Critical hit!** The {enemyName} gives you the people's elbow for {damage} damage!",
            $"💥 **Critical hit!** The {enemyName} uses forbidden knowledge for {damage} damage!",
            $"💥 **Critical hit!** The {enemyName} launches a high-speed baguette for {damage} damage!",
            $"💥 **Critical hit!** The {enemyName} triggers a Quick Time Event for {damage} damage!",
            $"💥 **Critical hit!** The {enemyName} activates its trap card for {damage} damage!",
            $"💥 **Critical hit!** The {enemyName} double-dips on damage for {damage} damage!",
            $"💥 **Critical hit!** The {enemyName} turns Super Ultra Instinct for {damage} damage!",
            $"💥 **Critical hit!** The {enemyName} breaks the fourth wall for {damage} damage!"
        };

        // Player tar skada
        public static string[] PlayerHpLines(string playerName, int hp, int maxHp) => new[]
        {
            $"{playerName} now has {hp}/{maxHp} HP remaining.",
            $"{playerName} stumbles but remains standing at {hp}/{maxHp} HP.",
            $"{playerName} grits their teeth, HP: {hp}/{maxHp}.",
            $"{playerName} takes it like a champ. {hp}/{maxHp} HP left!",
            $"{playerName} wobbles but refuses to fall. {hp}/{maxHp} HP to go.",
            $"{playerName} coughs dramatically, HP at {hp}/{maxHp}.",
            $"{playerName} shrugs it off—barely. {hp}/{maxHp} HP.",
            $"{playerName} swears they felt that. {hp}/{maxHp} HP now.",
            $"{playerName}'s hair gets singed, HP: {hp}/{maxHp}.",
            $"{playerName} flexes and powers through. {hp}/{maxHp} HP.",
            $"{playerName} is still standing! {hp}/{maxHp} HP remaining.",
            $"{playerName} looks dazed. Only {hp}/{maxHp} HP left!",
            $"{playerName} wonders if that was supposed to hurt. {hp}/{maxHp} HP.",
            $"{playerName} checks for bruises, HP at {hp}/{maxHp}.",
            $"{playerName} feels it in their soul. {hp}/{maxHp} HP.",
            $"{playerName} tries not to cry. {hp}/{maxHp} HP.",
            $"{playerName} considers calling mom. {hp}/{maxHp} HP.",
            $"{playerName} wishes they wore more armor. {hp}/{maxHp} HP.",
            $"{playerName} screams internally. {hp}/{maxHp} HP.",
            $"{playerName} powers through the pain. {hp}/{maxHp} HP.",
            $"{playerName}'s knees are shaky. {hp}/{maxHp} HP.",
            $"{playerName} spits out a tooth (probably not theirs). {hp}/{maxHp} HP.",
            $"{playerName} claims it's just a scratch. {hp}/{maxHp} HP.",
            $"{playerName} might need a band-aid. {hp}/{maxHp} HP.",
            $"{playerName} puts on a brave face. {hp}/{maxHp} HP.",
            $"{playerName} says 'I've had worse.' {hp}/{maxHp} HP.",
            $"{playerName} uses 10% more willpower. {hp}/{maxHp} HP.",
            $"{playerName} reconsiders their life choices. {hp}/{maxHp} HP.",
            $"{playerName} takes a selfie mid-battle. {hp}/{maxHp} HP.",
            $"{playerName} says 'Ow.' {hp}/{maxHp} HP."
        };

        // Defeat lines
        public static string[] DefeatLines(string playerName, string enemyName) => new[]
        {
            $"💀 {playerName} slips on a banana peel and is KO'd by the {enemyName}!",
            $"💀 {playerName} faints after seeing the {enemyName} do a Fortnite dance.",
            $"💀 {playerName} falls to the ground, defeated by the {enemyName}!",
            $"💀 The {enemyName} flexes, and {playerName} just can't handle it.",
            $"💀 {playerName} gets so dizzy they forget their own name. {enemyName} claims victory!",
            $"💀 {playerName} yells 'NOOOO!' as the {enemyName} wins.",
            $"💀 {playerName} faceplants into the dirt. {enemyName}: 1, {playerName}: 0.",
            $"💀 The {enemyName} dabs on {playerName}'s corpse.",
            $"💀 {playerName} is now a certified meme, thanks to the {enemyName}.",
            $"💀 {playerName} accidentally rage-quits IRL. {enemyName} is triumphant.",
            $"💀 {playerName} tries to respawn, but the {enemyName} blocks the attempt.",
            $"💀 {playerName} experiences maximum embarrassment. The {enemyName} eats a sandwich.",
            $"💀 {playerName} is sent flying like Team Rocket, courtesy of {enemyName}.",
            $"💀 The {enemyName} updates its status: 'GG EZ'.",
            $"💀 {playerName} is now trending on FailArmy. The {enemyName} celebrates.",
            $"💀 {playerName} gets flattened like a pancake. {enemyName} wipes syrup off its hands.",
            $"💀 {playerName}'s HP hits zero and their will to live follows. {enemyName} dances.",
            $"💀 {playerName} turns to dust. The {enemyName} sneezes.",
            $"💀 {playerName} is KO’d by sheer cringe. {enemyName} moonwalks away.",
            $"💀 {playerName} mistakes the exit for a hiding spot. {enemyName} just shrugs.",
            $"💀 {playerName} throws in the towel. The {enemyName} uses it as a cape.",
            $"💀 {playerName} is out of continues. {enemyName} starts a new game.",
            $"💀 {playerName} is hit so hard, they change character class. {enemyName} is impressed.",
            $"💀 {playerName} pulls a dramatic faint. The {enemyName} isn’t buying it.",
            $"💀 {playerName} lags out—physically. The {enemyName} facepalms.",
            $"💀 {playerName}'s soul leaves the chat. {enemyName} says 'GG.'",
            $"💀 {playerName} becomes an urban legend. The {enemyName} signs autographs.",
            $"💀 {playerName} goes to the shadow realm. {enemyName} waves goodbye.",
            $"💀 {playerName} is now one with the floor. The {enemyName} tiptoes away.",
            $"💀 {playerName} loses consciousness and the {enemyName} loots their socks."
        };

        private static string Capitalize(this string s)
            => string.IsNullOrEmpty(s) ? s : char.ToUpper(s[0]) + s.Substring(1);
    }
}
